site_name: ALM

nav:
  - Sobre: index.md
  - Relatório de Status: artefatos/relatorio-semanal.md
  - Atas: artefatos/atas-reunioes.md
  - Artefatos:
      - Termo de Abertura do Projeto: artefatos/tap.md
      - Termo de Acordo de Serviço: artefatos/ts.md
      - Acordos de Serviço:
          - Termo de Acordo de Serviço (Equipe Gestão de Ativos): artefatos/acordo-equipe_ativos.md
          - Termo de Acordo de Serviço (Equipe Gestão de Passivos): artefatos/acordo-equipe_passivos.md
          - Termo de Acordo de Serviço (Equipe Gestão de Riscos): artefatos/acordo-equipe_riscos.md
      - Documento de Arquitetura de Software:

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true

theme:
  name: "material"
  palette:
    primary: light green
    accent: deep orange
  theme:
    font:
      text: Ubuntu
      code: Ubuntu Mono
