site_name: ALM

nav:
  - Sobre: index.md
  - Artefatos:
    - Termo de Abertura do Projeto: artefatos/tap.md
    - Termo de Acordo de Serviço: artefatos/ts.md

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true

theme:
  name: 'material'
  palette:
    primary: light green
    accent: deep orange 
  theme:
    font:
      text: Ubuntu
      code: Ubuntu Mono
